# Texto a utilizar

In [132]:
text = """El aprendizaje automático está transformando la industria.
El aprendizaje está transformando los modelos de lenguaje.
Los modelos de lenguaje son un claro de revolución tecnológica.
La industria de la revolución tecnológica está cambiando con el aprendizaje automático.
El aprendizaje está transformando todo"""

# Limpieza del texto

In [133]:
text = text.lower()

In [134]:
text = text.replace(". \n", " ")

In [135]:
text

'el aprendizaje automático está transformando la industria el aprendizaje está transformando los modelos de lenguaje los modelos de lenguaje son un claro de revolución tecnológica la industria de la revolución tecnológica está cambiando con el aprendizaje automático el aprendizaje está transformando todo'

# Matrices

## Matriz de adyacencia

In [136]:
import pandas as pd

words = text.split()

bigrams = [(words[i], words[i+1]) for i in range(len(words)-1)]

df_temp = pd.DataFrame(bigrams, columns=['Word-1', 'Word-2'])

matrix = pd.crosstab(df_temp['Word-1'], df_temp['Word-2'])

matrix

Word-2,aprendizaje,automático,cambiando,claro,con,de,el,está,industria,la,lenguaje,los,modelos,revolución,son,tecnológica,todo,transformando,un
Word-1,,,,,,,,,,,,,,,,,,,
aprendizaje,0,2,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0
automático,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0
cambiando,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
claro,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
con,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
de,0,0,0,0,0,0,0,0,0,1,2,0,0,1,0,0,0,0,0
el,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
está,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0
industria,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0
la,0,0,0,0,0,0,0,0,2,0,0,0,0,1,0,0,0,0,0
lenguaje,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0
los,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0
modelos,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0
revolución,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0
son,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
tecnológica,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0
transformando,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0
un,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

## Matriz de probabilidad

In [137]:
matrix_percentages = matrix.div(matrix.sum(axis=1), axis=0)

matrix_percentages = matrix_percentages.fillna(0)

matrix_percentages.round(2)

Word-2,aprendizaje,automático,cambiando,claro,con,de,el,está,industria,la,lenguaje,los,modelos,revolución,son,tecnológica,todo,transformando,un
Word-1,,,,,,,,,,,,,,,,,,,
aprendizaje,0.0,0.5,0.00,0.0,0.0,0.0,0.0,0.5,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.0
automático,0.0,0.0,0.00,0.0,0.0,0.0,0.5,0.5,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.0
cambiando,0.0,0.0,0.00,0.0,1.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.0
claro,0.0,0.0,0.00,0.0,0.0,1.0,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.0
con,0.0,0.0,0.00,0.0,0.0,0.0,1.0,0.0,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.0
de,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.25,0.5,0.00,0.0,0.25,0.0,0.0,0.00,0.00,0.0
el,1.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.0
está,0.0,0.0,0.25,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.00,0.75,0.0
industria,0.0,0.0,0.00,0.0,0.0,0.5,0.5,0.0,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.0
la,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.67,0.00,0.0,0.00,0.0,0.33,0.0,0.0,0.00,0.00,0.0
lenguaje,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.50,0.0,0.00,0.5,0.0,0.00,0.00,0.0
los,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,1.0,0.00,0.0,0.0,0.00,0.00,0.0
modelos,0.0,0.0,0.00,0.0,0.0,1.0,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.0
revolución,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.00,0.0,1.0,0.00,0.00,0.0
son,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.00,0.00,1.0
tecnológica,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.5,0.00,0.50,0.0,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.0
transformando,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.33,0.0,0.33,0.0,0.00,0.0,0.0,0.33,0.00,0.0
un,0.0,0.0,0.00,1.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.0

## Generador de frases

In [138]:
import pandas as pd
import numpy as np

def generate_frase(df_matrix, start_word, length=5):
    # Asegurarnos de que no usamos la columna 'Suma' para elegir palabras

    frase = [start_word]
    current_word = start_word

    for _ in range(length - 1):
        if current_word in matrix.index:
            # Obtenemos la fila de la palabra actual
            distribution = matrix.loc[current_word]

            # Si todas las frecuencias son 0, nos detenemos o elegimos una al azar
            if distribution.sum() == 0:
                break

            # Elegimos la siguiente palabra basada en las frecuencias (pesos)
            next = np.random.choice(distribution.index, p=distribution/distribution.sum())
            frase.append(next)
            current_word = next
        else:
            break

    return " ".join(frase)

start_word = np.random.choice(matrix.index)
frase_1 = generate_frase(matrix, start_word, length=5)

start_word = np.random.choice(matrix.index)
frase_2 = generate_frase(matrix, start_word, length=5)

print(f"Frase 1: {frase_1}")
print(f"Frase 2: {frase_2}")

Frase 1: automático está transformando la industria
Frase 2: modelos de lenguaje son un

# Cálculo de perplejidad

## Función de perplejidad:
#### $Pp(W) = \sqrt[N]{\frac{1}{P(w_{1}w_{2}...w_{N})}}$

## Calculamos la cantidad de bigramas totales (nuestra $N$)

In [139]:
bigrams_list = [(words[i], words[i+1]) for i in range(len(words)-1)]

N = len(bigrams_list)

## Creamos una función que calcule la perplejidad

In [140]:
def calculate_perplexity(frase):
  # Creamos el arreglo con las palabras de la frase
  words = frase.split()

  # Inicializamos la variable de la probabilidad
  probability = 1;

  # Recorremos el arreglo de palabras multiplicando sus probabilidades
  for index in range(len(words) - 1):
    probability *= (matrix_percentages.at[words[index], words[index + 1]])

  # Retornamos la perplejidad
  return (1/probability)**(1/N)

## Calculamos la perplejidad de las 2 oraciones generadas

In [141]:
print(f'Cantidad de bigramas totales (N): {N}')
print(f'\n{50 * "-"}\n')

print(f'Frase 1: {frase_1}')
print(f'Perplejidad: {calculate_perplexity(frase_1)}')

print(f'\n{50 * "-"}\n')

print(f'Frase 2: {frase_2}')
print(f'Perplejidad: {calculate_perplexity(frase_2)}')

Cantidad de bigramas totales (N): 41

--------------------------------------------------

Frase 1: automático está transformando la industria
Perplejidad: 1.062481786193221

--------------------------------------------------

Frase 2: modelos de lenguaje son un
Perplejidad: 1.0343901826728465